version: '3'

services:
  customerservice:
    environment:
      - ASPNETCORE_ENVIRONMENT=Development
    ports:
      - "80"

  vetservice:
    environment:
      - ASPNETCORE_ENVIRONMENT=Development
    ports:
      - "80"


  testapplication:
    environment:
      - ASPNETCORE_ENVIRONMENT=Development
    ports:
      - "80"

