language: csharp
sudo: required
dist: trusty
mono: none
dotnet: SDK 2.1.300-preview2-008533
install:
  - export DOTNET_CLI_TELEMETRY_OPTOUT=1
before_script:
  - chmod a+x ./build.sh
  - chmod a+x ./deploy.sh
script:
  - ./build.sh
deploy:
  - provider: script
    script: ./deploy.sh $TRAVIS_TAG
    skip_cleanup: true
    on:
      tags: true
 
