apiVersion: extensions/v1beta1
kind: Deployment
metadata:
  name: petclinic-app
spec:
  replicas: 1
  template:
    metadata:
      labels:
        run: petclinic-app
    spec:
      containers:
      - name: angular-app
        image: gcr.io/certificationproject-238411/petclinicfrontend
        ports:
        - containerPort: 80
          protocol: TCP
