apiVersion: extensions/v1beta1
kind: Deployment
metadata:
  name: petclinic-restservice
  namespace: default
spec:
  template:
    metadata:
      labels:
        run: petclinic-restservice
    spec:
      containers:
      - env:
        image: gcr.io/pet-clinic-235417/petclinicrestservice:latest
        name: petclinic-restservice
        ports:
        - containerPort: 80
          protocol: TCP
      - command:
        - /cloud_sql_proxy
        - -instances=pet-clinic-235417:us-central1:petclinic=tcp:3307
        - -credential_file=/secrets/cloudsql/key.json
        image: gcr.io/cloudsql-docker/gce-proxy:1.11
        name: cloudsql-proxy
        volumeMounts:
        - mountPath: /secrets/cloudsql
          name: cloudsql-instance-credentials
          readOnly: true
      volumes:
      - name: cloudsql-instance-credentials
        secret:
          secretName: pet-key
