apiVersion: extensions/v1beta1
kind: Deployment
metadata:
  name: petclinic-restservice
  namespace: default
spec:
  template:
    metadata:
      labels:
        run: petclinic-restservice
    spec:
      containers:
      - env:
        image: gcr.io/certificationproject-238515/petclinic-restservice
        name: petclinic-restservice
        ports:
        - containerPort: 80
          protocol: TCP
      - command:
        - /cloud_sql_proxy
        - -instances=certificationproject-238515:us-central1:petclininc-instance-1=tcp:3307
        - -credential_file=/secrets/cloudsql/sqlaccesskey.json
        image: gcr.io/cloudsql-docker/gce-proxy:1.11
        name: cloudsql-proxy
        volumeMounts:
        - mountPath: /secrets/cloudsql
          name: cloudsql-instance-credentials
          readOnly: true
      volumes:
      - name: cloudsql-instance-credentials
        secret:
          secretName: credentials
