apiVersion: extensions/v1beta1
kind: Deployment
metadata:
  name: petclinic-restservice
  namespace: default
spec:
  template:
    metadata:
      labels:
        run: petclinic-restservice
    spec:
      containers:
      - name: petclinic-restservice
        image: gcr.io/certificationproject-238515/petclinic-restservice 
        env:
        - name: "ASPNETCORE_ENVIRONMENT"
          value: "Kubernetes"
        ports:
        - containerPort: 80
          protocol: TCP
        volumeMounts:
        - name : backend-configmap
          mountPath: /app/appsettings.json
          readOnly: true
          subPath: appsettings.json
      - command:
        - /cloud_sql_proxy
        - -instances=certificationproject-238515:us-central1:petclininc-instance-1=tcp:3307
        - -credential_file=/secrets/cloudsql/sqlaccesskey.json
        image: gcr.io/cloudsql-docker/gce-proxy:1.11
        name: cloudsql-proxy
        volumeMounts:
        - mountPath: /secrets/cloudsql
          name: cloudsql-instance-credentials
          readOnly: true
      volumes:
      - name: cloudsql-instance-credentials
        secret:
          secretName: credentials
      - name: backend-configmap
        configmap:
          name: backendconfig
