apiVersion: v1
kind: Service
metadata:
  labels:
    run: petclinic-restservice
  name: petclinic-restservice
  namespace: default
spec:
  ports:
  - nodePort: 31596
    port: 80
    protocol: TCP
    targetPort: 80
  selector:
    app: petclinic-restservice
    run: petclinic-restservice
  sessionAffinity: None
  type: LoadBalancer
status:
  loadBalancer:
    ingress:
    - ip: 34.73.122.77
